services:
    frontend:
        build: ./frontend
        ports:
            - 80:80
    backend:
        build: ./backend
        ports:
            - 8000:8000
        environment:
            - OUTPUT_FOLDER=output
        volumes:
          - ./backend/output:/app/output
